version: '3.9'
services:
  php-apache-environment:
    container_name: php-apache
    # image: php:8.0-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8080:80
    networks:
      my-apache:

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - '9906:3306'
    networks:
      my-apache:

networks:
  # my-bridge-001:
  #   external:
  #     name: my-bridg1001
  my-apache:
    ipam:
      driver: default
      config:
        - subnet: 172.31.40.0/24
